### ISSUE TITLE
Works with G14

### ISSUE THREAD

**Issue by aminoa** [NeilSeligmann/G15Manager#1]
My G14 GA401QM is able to use all the functionality when using the web app. It didn't work with G14Manager.

**Comment by NeilSeligmann** [comment]
Thats great! Do all of the functions work?
Sorry for the late response.

**Comment by aminoa** [comment]
I don't have it on my machine currently but I remember the power profile switching worked (though I think the high performance plan needed some extra configuration to work) and the zephyrus function key replacements (so opening the ROGManager app, toggling airplane mode, backlight brightness control, etc) worked.

**Comment by NeilSeligmann** [comment]
I've now added it to the [README](https://github.com/NeilSeligmann/G15Manager/blob/3d5ea073f89598de1c17994cf606ad863177c4c2/README.md) file, thanks!
